// Generated by CoffeeScript 1.11.1
(function() {
  $(document).ready(function() {
    var c, ctx;
    c = $("#board").get(0);
    ctx = c.getContext("2d");
    ctx.beginPath();
    ctx.arc(200, 200, 100, 0, 2 * Math.PI);
    ctx.fillStyle = "#FF0000";
    return ctx.fill();
  });

}).call(this);
