language: python
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py collectstatic --no-input
  - coverage run --source=accounts,chat,game_board manage.py test accounts chat
after_success:
  coveralls
