# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 12:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_list_of_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='list_of_friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
