# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_list_of_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 31, 19, 24, 32, 130970)),
        ),
    ]
