# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161229_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 12, 38, 30, 856093)),
        ),
    ]
