# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170115_2013'),
        ('accounts', '0008_auto_20170115_2000'),
    ]

    operations = [
    ]
