# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170115_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 20, 38, 44, 69218)),
        ),
    ]
