# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170115_2038'),
        ('accounts', '0009_auto_20170115_2032'),
    ]

    operations = [
    ]
