# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='label',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
