# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.3 on 2017-01-15 20:13
from __future__ import unicode_literals

=======
# Generated by Django 1.10.3 on 2017-01-15 20:00
from __future__ import unicode_literals

from django.conf import settings
>>>>>>> master
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('accounts', '0008_auto_20170115_2013'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> master
        ('game_board', '0002_player_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
<<<<<<< HEAD
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
=======
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
>>>>>>> master
            preserve_default=False,
        ),
    ]
